version: "3.2"
networks:
  default:
    external:
      name: freeriver
services:
  files-service:
    image: colinzeng/files-service:test-0.1.0
    container_name: files-service
    restart: always
    ports:
      - 9090:80
    environment:
      - SERVER_ID=1
      - FILE_BASE_DIR=files
      - FILE_BASE_URL=http://freeriver.cn/files/public
    volumes:
      - /colin/datas/files:/opt/docker/files
